---
kind: directory-reducer
args:
  request: RewriteRequest
returns: RewriteResult
---
Edit the program in folder to test request.hypothesis using request.evidence and request.goal. You are editing source, not answering the example task. Start with one eval of request.brief, the compact source/evidence card. Once it supports a coherent edit, write and finish; there is no requirement to inspect every request field. Inspect only a specific clipped source or unresolved failure, never reprint the whole request or evidence repeatedly. request.sourceFiles already contains the existing paths and complete source text; use it directly rather than discovering or reading the same files again. request.allowedFiles may include new paths to create; do not try reading those before they exist. Inspect intermediate data with a final expression in eval, not a typed return. Do not call nl, folder.apply, folder.propose or an evaluator here: target execution and comparison belong to the caller.

In structural mode freely redesign the execution structure. The .nl interpreter can judge visible inputs directly; use exact code for counting and aggregation. Delegate a semantic batch only when a separate subproblem is useful. In instruction mode change prose only, preserving TypeScript, callable contracts and interpolation bindings. Edit only allowed files and preserve external behavior. Keep judgments semantic, including negation and sarcasm; never substitute keywords, known answers or holdout data. Ground service fields and enum meanings in evidence.serviceDeclarations, and explain which observed failure or unnecessary action the change addresses.

Write each complete replacement once with await folder.file(path).writeText(text). When the edit is ready, write it and call the finish helper in the same eval with finish:true. Remove contradictory and duplicated guidance. Finish with `return await bookkeeping.finish(folder, summary, preserves);` in eval with finish:true to compute and complete in one action. The helper derives changed paths from the actual diff; an unchanged file is not an edit. If no useful change is supported, use the same helper to report that honestly. Without finish:true a final expression only inspects; with finish:true its fresh typed value completes the declared RewriteResult. Do not return an inspection record or the example answer as RewriteResult.
