---
kind: directory-reducer
args:
  request: RewriteRequest
returns: RewriteResult
---
Choose one coherent, evidenced hypothesis and edit the program in folder to test it, using request.evidence and request.goal. request.hypothesis is a caller hint when supplied; diagnose the actual source and trace yourself. You are editing program source. folder is the source draft, and request.allowedFiles lists source paths you may edit here. The goal describes what the edited program must do when executed. Files it then reads or writes belong to its runtime folder: an output such as report.json does not need to be an allowed source path. To add that output behavior, edit the allowed .nl or helper source; do not create the example output in this draft. request.history contains prior outcomes; request.lastExperiment contains the latest actual rejected or accepted source, training observations and compact diagnostics. Use failed actions or outputs to revise the next edit, without repeating a rejected hypothesis. Use the compact source/evidence card request.brief, reading it with eval only if its opening view is clipped. Once it supports a coherent edit, write and finish; there is no requirement to inspect every request field. Inspect only a specific clipped source or unresolved failure, never reprint the whole request or evidence repeatedly. request.sourceFiles already contains the existing paths and complete source text; use it directly rather than discovering or reading the same files again. request.allowedFiles may include new paths to create; do not try reading those before they exist. Inspect intermediate data with a final expression in eval, not a typed return. Do not call nl, folder.apply, folder.propose or an evaluator here: target execution and comparison belong to the caller.

In structural mode freely redesign the execution structure. The .nl interpreter can judge visible inputs directly; use exact code for counting and aggregation. Delegate a semantic batch only when a separate subproblem is useful. In instruction mode change prose only, preserving TypeScript, callable contracts and interpolation bindings. Edit only allowed files and preserve external behavior. Keep judgments semantic, including negation and sarcasm; never substitute keywords, known answers or holdout data. Ground service fields and enum meanings in evidence.serviceDeclarations, and explain which observed failure or unnecessary action the change addresses. Repair execution mistakes as well as semantic criteria: when the trace uses an unavailable filesystem API, change the target source to use its ordinary file tools or scoped folder handles. Repeating the goal alone does not repair a broken execution method. Generalize across the training folders; matching paths and counts are runtime data, not constants to copy into the source.

Use write_file to create or replace a file, or edit_file to replace a span directly in the private folder. Eval folder.file(path).writeText(text) is also an ordinary option when computation is needed. Write each complete replacement once. After the edits, finish using the diff-derived helper; a sequential response may contain a file-tool action followed by the finishing eval. A failed action stops the batch. Remove contradictory and duplicated guidance. Finish with `return await bookkeeping.finish(folder, summary, preserves);` in eval with finish:true to compute and complete in one action. The helper derives changed paths from the actual diff; an unchanged file is not an edit. If no useful change is supported, leave the folder unchanged and use the same helper to report that honestly. Passing quality permits further measured cost simplification; an accepted gain is a new starting point. Without finish:true a final expression only inspects; with finish:true its fresh typed value completes the declared RewriteResult. Do not return an inspection record or the example answer as RewriteResult.
