/** Hand-authored semantic repair cases. The bad eval must fail in the native runtime. */
export const failureCases = [
  {
    id: 'customer-foreign-key', family: 'relational-join',
    insight: 'The order ID and customer foreign key are different domains; the failed lookup joins on a numeric subtotal.',
    type: '(order: { customerId: string, subtotal: number }, customers: { id: string, tier: string }[]) => number',
    instructions: 'Find the order customer by customerId. Apply a 10% discount to the subtotal only for a gold customer, and return the amount.',
    inputs: { order: { customerId: 'c-2', subtotal: 80 }, customers: [{ id: 'c-1', tier: 'gold' }, { id: 'c-2', tier: 'gold' }] },
    failed: 'const customer = customers.find(c => c.id === String(order.subtotal))!; result = customer.tier === "gold" ? order.subtotal * 0.9 : order.subtotal;',
    repaired: 'const customer = customers.find(c => c.id === order.customerId)!; result = customer.tier === "gold" ? order.subtotal * 0.9 : order.subtotal;',
    expected: 72,
  },
  {
    id: 'normalized-identity', family: 'normalization',
    insight: 'Identity comparison needs trim and case folding on both sides; the failed lookup assumes presentation strings are canonical.',
    type: '(email: string, blocked: { email: string, reason: string }[]) => string',
    instructions: 'Return the reason for a blocked email address, comparing addresses case-insensitively after trimming surrounding whitespace.',
    inputs: { email: '  Ada@Example.COM ', blocked: [{ email: 'ada@example.com', reason: 'manual review' }] },
    failed: 'result = blocked.find(entry => entry.email === email)!.reason;',
    repaired: 'const key = email.trim().toLowerCase(); result = blocked.find(entry => entry.email.trim().toLowerCase() === key)!.reason;',
    expected: 'manual review',
  },
  {
    id: 'revision-as-of', family: 'temporal-selection',
    insight: 'Array order is not revision order; a key can have multiple historical versions and the cutoff is inclusive.',
    type: '(key: string, cutoff: number, versions: { key: string, revision: number, value: string }[]) => string',
    instructions: 'Return the value for the highest revision of key that is no later than cutoff.',
    inputs: { key: 'feature', cutoff: 4, versions: [
      { key: 'feature', revision: 2, value: 'old' }, { key: 'other', revision: 4, value: 'noise' },
      { key: 'feature', revision: 4, value: 'current' }, { key: 'feature', revision: 7, value: 'future' }] },
    failed: 'const selected = versions.find(v => v.key === key)!; if (selected.revision !== cutoff) throw new Error("revision invariant failed"); result = selected.value;',
    repaired: 'const eligible = versions.filter(v => v.key === key && v.revision <= cutoff); eligible.sort((a, b) => b.revision - a.revision); result = eligible[0].value;',
    expected: 'current',
  },
  {
    id: 'localized-money', family: 'parsing',
    insight: 'The grouping separator is a dot and the decimal separator is a comma; Number(raw) is NaN.',
    type: '(raw: string) => number',
    instructions: 'Parse a euro amount formatted with a € prefix, dots as thousands separators, and a comma as decimal separator. Return integer cents.',
    inputs: { raw: '€ 1.234,56' },
    failed: 'const cents = Math.round(Number(raw.replace("€", "").trim()) * 100); if (!Number.isFinite(cents)) throw new Error("invalid amount"); result = cents;',
    repaired: 'const normalized = raw.replace("€", "").trim().replaceAll(".", "").replace(",", "."); result = Math.round(Number(normalized) * 100);',
    expected: 123456,
  },
  {
    id: 'sparse-neighbors', family: 'sparse-structure',
    insight: 'Neighbor cells may be absent even when a row exists; the computation must count only present numeric cells.',
    type: '(grid: number[][], row: number, col: number) => number',
    instructions: 'Sum existing numeric cells directly above, below, left, and right of the selected cell. Missing neighbors contribute zero.',
    inputs: { grid: [[3], [4, 5, 6], [7, 8]], row: 1, col: 1 },
    failed: 'const total = grid[row - 1][col] + grid[row + 1][col] + grid[row][col - 1] + grid[row][col + 1]; if (!Number.isFinite(total)) throw new Error("non-rectangular grid"); result = total;',
    repaired: 'const neighbors = [grid[row - 1]?.[col], grid[row + 1]?.[col], grid[row]?.[col - 1], grid[row]?.[col + 1]].map(value => value ?? 0); result = neighbors.reduce((sum, value) => sum + value, 0);',
    expected: 18,
  },
  {
    id: 'specific-rule-wins', family: 'precedence',
    insight: 'Two rules match; selecting the first matching rule loses the higher-priority override.',
    type: '(score: number, rules: { min: number, max: number, priority: number, label: string }[]) => string',
    instructions: 'Among inclusive range rules matching score, return the label of the highest-priority rule.',
    inputs: { score: 87, rules: [{ min: 0, max: 100, priority: 1, label: 'standard' },
      { min: 80, max: 90, priority: 9, label: 'review' }] },
    failed: 'const match = rules.find(rule => score >= rule.min && score <= rule.max)!; if (match.priority < 9) throw new Error("rule precedence violated"); result = match.label;',
    repaired: 'const matching = rules.filter(rule => score >= rule.min && score <= rule.max); matching.sort((a, b) => b.priority - a.priority); result = matching[0].label;',
    expected: 'review',
  },
  {
    id: 'nested-configuration-overlay', family: 'fallback-semantics',
    insight: 'An absent nested override means inherit the global value; it is not an error or an empty string.',
    type: '(app: { theme: { accent: string } }, global: { theme: { accent: string } }) => string',
    instructions: 'Return the application accent color when nonempty; otherwise inherit the global accent color.',
    inputs: { app: { theme: { accent: '' } }, global: { theme: { accent: '#3267ad' } } },
    failed: 'const chosen = app.theme.accent; if (!chosen) throw new Error("accent missing"); result = chosen.toUpperCase();',
    repaired: 'result = app.theme.accent || global.theme.accent;',
    expected: '#3267ad',
  },
  {
    id: 'settled-ledger', family: 'state-and-sign',
    insight: 'Only settled entries count and refunds subtract rather than add; a mixed ledger cannot be summed naively.',
    type: '(entries: { status: string, kind: string, cents: number }[]) => number',
    instructions: 'Return net settled cents: settled charges add, settled refunds subtract, and pending entries do not count.',
    inputs: { entries: [{ status: 'settled', kind: 'charge', cents: 700 },
      { status: 'pending', kind: 'charge', cents: 900 }, { status: 'settled', kind: 'refund', cents: 120 }] },
    failed: 'const total = entries.reduce((sum, entry) => sum + entry.cents, 0); if (total > 1000) throw new Error("ledger does not reconcile"); result = total;',
    repaired: 'result = entries.filter(entry => entry.status === "settled").reduce((sum, entry) => sum + (entry.kind === "refund" ? -entry.cents : entry.cents), 0);',
    expected: 580,
  },
  {
    id: 'resettable-event-stream', family: 'event-reduction',
    insight: 'A reset event replaces the accumulator; treating it as a delta produces a non-finite state.',
    type: '(events: { kind: string, amount: number }[]) => number',
    instructions: 'Starting from zero, apply events in order. An add event increases the state by amount; a reset event replaces the state with amount.',
    inputs: { events: [{ kind: 'add', amount: 8 }, { kind: 'reset', amount: 3 }, { kind: 'add', amount: 4 }] },
    failed: 'const total = events.reduce((sum, event) => sum + (event.kind === "add" ? event.amount : Number(undefined)), 0); if (!Number.isFinite(total)) throw new Error("state became invalid"); result = total;',
    repaired: 'result = events.reduce((state, event) => event.kind === "reset" ? event.amount : state + event.amount, 0);',
    expected: 7,
  },
  {
    id: 'encoded-path-segments', family: 'representation-order',
    insight: 'Decoding before splitting turns an encoded slash inside one segment into a path separator.',
    type: '(path: string) => string',
    instructions: 'Return the decoded second slash-delimited path segment. A percent-encoded slash belongs inside its segment.',
    inputs: { path: 'teams/a%2Fb/profile' },
    failed: 'const parts = decodeURIComponent(path).split("/"); if (parts.length !== 3) throw new Error("unexpected segment count"); result = parts[1];',
    repaired: 'result = decodeURIComponent(path.split("/")[1]);',
    expected: 'a/b',
  },
];

export function failureProgramRecords() {
  return failureCases.map(item => ({
    version: 'natlang.program/1', id: `failure-repair:${item.id}`, kind: 'lambda_graph',
    family: `failure_repair/${item.family}`, split: 'train', source_groups: [`failure-repair:${item.id}`],
    curriculum_evidence: 'native_failed_eval_then_verified_teacher_repair',
    failure_insight: item.insight,
    semantics: { root: { $lambda: { type: item.type, instructions: item.instructions } },
      inputs: item.inputs, expected: item.expected,
      failure_seed: { code: item.failed, kind: 'runtime' } },
  }));
}
