#!/usr/bin/env node
/**
 * Embed the built-in natlang programs (src/builtin/*.nl) as src/builtin/sources.generated.ts, so the same bytes ship in
 * the Node build, the npm package and the browser bundle without file access at run time. The `.nl` files are the source;
 * `--check` fails when the generated module is stale. Usage: node scripts/generate-builtin.mjs [--check]
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const dir = resolve(import.meta.dirname, '../src/builtin');
const target = join(dir, 'sources.generated.ts');
const names = readdirSync(dir).filter(name => name.endsWith('.nl')).sort();
const text = `// Generated by scripts/generate-builtin.mjs from the .nl files in this folder. Do not edit; edit the .nl files and run
// \`node scripts/generate-builtin.mjs\` (npm run build:node does).
/** The built-in natlang programs by file name without \`.nl\`: the exact bytes of each file. */
export const BUILTIN_SOURCES: Readonly<Record<string, string>> = {
${names.map(name => `  ${JSON.stringify(name.slice(0, -3))}: ${JSON.stringify(readFileSync(join(dir, name), 'utf8'))},`).join('\n')}
};
`;
if (process.argv.includes('--check')) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== text) {
    console.error('src/builtin/sources.generated.ts is stale; run: node scripts/generate-builtin.mjs');
    process.exit(1);
  }
} else writeFileSync(target, text);
