#!/usr/bin/env node
/** Resolve one stable llama.cpp release into natlang's checked runtime manifest. */
import { randomUUID } from 'node:crypto';
import { rename, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repository = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const destination = resolve(repository, 'ts-host/src/llama-runtime-release.ts');
const args = process.argv.slice(2), value = name => args[args.indexOf(name) + 1];
const requested = value('--version');
if (!requested || !/^\d+\.\d+\.\d+$/.test(requested))
  throw new Error('usage: node scripts/update_llama_runtime.mjs --version X.Y.Z');

const headers = { accept: 'application/vnd.github+json', 'user-agent': 'natlang-runtime-publisher' };
async function getJson(url) {
  const response = await fetch(url, { headers });
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.json();
}
async function getText(url) {
  const response = await fetch(url, { headers });
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return (await response.text()).trim();
}

const stable = await getJson(`https://api.github.com/repos/ggml-org/llama.cpp/releases/tags/v${requested}`);
const pointer = stable.assets.find(asset => asset.name === 'nightly-tag.txt');
if (!pointer) throw new Error(`v${requested} has no signed build pointer`);
const buildTag = await getText(pointer.browser_download_url);
const buildMatch = /^b(\d+)$/.exec(buildTag);
if (!buildMatch) throw new Error(`invalid llama.cpp build tag: ${buildTag}`);
const build = Number(buildMatch[1]);
const [release, commit] = await Promise.all([
  getJson(`https://api.github.com/repos/ggml-org/llama.cpp/releases/tags/${buildTag}`),
  getJson(`https://api.github.com/repos/ggml-org/llama.cpp/commits/${buildTag}`),
]);
const definitions = [
  ['linux-x64-cpu', 'linux', 'x64', 'cpu', 'tar.gz', `llama-${buildTag}-bin-ubuntu-x64.tar.gz`],
  ['linux-arm64-cpu', 'linux', 'arm64', 'cpu', 'tar.gz', `llama-${buildTag}-bin-ubuntu-arm64.tar.gz`],
  ['darwin-arm64-metal', 'darwin', 'arm64', 'metal', 'tar.gz', `llama-${buildTag}-bin-macos-arm64.tar.gz`],
  ['darwin-x64-metal', 'darwin', 'x64', 'metal', 'tar.gz', `llama-${buildTag}-bin-macos-x64.tar.gz`],
  ['win32-x64-cpu', 'win32', 'x64', 'cpu', 'zip', `llama-${buildTag}-bin-win-cpu-x64.zip`],
  ['win32-arm64-cpu', 'win32', 'arm64', 'cpu', 'zip', `llama-${buildTag}-bin-win-cpu-arm64.zip`],
];
const artifacts = definitions.map(([key, platform, arch, backend, archive, name]) => {
  const asset = release.assets.find(candidate => candidate.name === name);
  if (!asset || !/^sha256:[0-9a-f]{64}$/.test(asset.digest ?? ''))
    throw new Error(`${buildTag} is missing a digest-bearing ${name}`);
  return { key, platform, arch, backend, archive, url: asset.browser_download_url,
    bytes: asset.size, sha256: asset.digest.slice('sha256:'.length) };
});
const [major, minor] = requested.split('.').map(Number);
const manifest = { version: requested, build, commit: commit.sha.slice(0, 9),
  compatible: { minimumVersion: requested, maximumVersionExclusive: `${major}.${minor + 1}.0`, minimumBuild: build },
  artifacts };
const source = `/** Generated by scripts/update_llama_runtime.mjs; do not edit by hand. */
import type { LlamaRuntimeRelease } from './model/llama-runtime.js';

export const LLAMA_RUNTIME_RELEASE = Object.freeze(${JSON.stringify(manifest, null, 2)} satisfies LlamaRuntimeRelease);
`;
const temporary = `${destination}.${randomUUID()}.tmp`;
await writeFile(temporary, source);
await rename(temporary, destination);
process.stdout.write(JSON.stringify({ version: requested, build, commit: manifest.commit,
  artifacts: artifacts.map(artifact => artifact.key) }) + '\n');
