"""Schnitzeljagd episode corpora (`tasks-*`) → port records (S1 §3.3, §4.2).

Episodes carry `query`, `answer`, `supports` (record texts), `required_ids`, `sufficient_groups`,
`verify` and `provenance`. Converters keep the supports as sources, rephrase "Use the stored …"
queries as ordinary consumer requests, keep `required_ids` only as a provenance note, and drop
bank, key and retrieval framing. Multi-turn agent episodes (`turns`) are left to a later converter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from .common import Reject, jsonl_rows
from .records import VERSION, group_key, license_, seal, source, strip_markup

CORPORA_DIR = Path("/mnt/external/sdkb-archive/corpora")
ARCHIVE_ROOT = "/mnt/external/sdkb-archive"
CONVERTER = "scripts/neuralese_data/schnitzel.py@1"

_STORED_RE = re.compile(r"^\s*Use the stored (?P<noun>[^\n]*?)\.\s*", re.S)

# domain → (family, upstream, licence (spdx, noncommercial, notes))
DOMAINS = {
    "recall_text": ("recall_text", "wikipedia", ("CC-BY-SA-4.0", False, "")),
    "parallel-recall": ("recall_parallel", "scrollmapper/bible_databases", ("LicenseRef-PublicDomain", False, "Public-domain or CC0 Bible translations; per-source licences recorded.")),
    "citance_recall": ("recall_citance", "unarXive_citrec + OpenAlex", ("LicenseRef-mixed-open", False, "Citing papers: CC-BY-4.0 89%, CC-BY-SA-4.0 5%, CC0 5%, other 1%; per-source licences recorded.")),
    "synth_people": ("qa_synthetic_people", "schnitz.synth_world", ("LicenseRef-generated", False, "Synthetic world generated by Schnitzeljagd.")),
    "spider": ("text_to_sql", "spider", ("CC-BY-SA-4.0", False, "")),
    "bird": ("text_to_sql", "bird-bench", ("CC-BY-SA-4.0", False, "")),
    "spider_memory": ("table_qa_stored", "spider", ("CC-BY-SA-4.0", False, "Table contents of Spider databases; answers are values.")),
    "xlam": ("function_call", "Salesforce/xlam-function-calling-60k", ("CC-BY-4.0", False, "Gated upstream; access terms recorded in the ledger.")),
    "knights": ("reasoning_knights", "knights-and-knaves", ("LicenseRef-unverified", False, "Licence to be verified from the upstream card.")),
    "kodcode": ("code_python", "KodCode/KodCode-V1", ("CC-BY-NC-4.0", True, "")),
    "synlogic": ("reasoning_synlogic", "MiniMaxAI/SynLogic", ("LicenseRef-unverified", False, "Licence to be verified from the upstream card.")),
    "reasoning_gym": ("reasoning_gym", "open-thought/reasoning-gym", ("Apache-2.0", False, "")),
}
# Corpora converted in this first wave: single-turn episodes.
CORPORA = [
    "tasks-recall-text-r8-20260928", "tasks-recall-text-r2-20260928", "tasks-parallel-recall-20260928",
    "tasks-parallel-recall-hard-20260928", "tasks-citance-recall-20260928", "tasks-synth-people-r4-20260928",
    "tasks-synth-people-r32-20260928", "tasks-spider-20260927", "tasks-spider-bg-20260927", "tasks-bird-20260927",
    "tasks-bird-bg-20260927", "tasks-spider-memory-20260927", "tasks-spider-memory-bg-20260927",
    "tasks-xlam-20260927", "tasks-knights-20260927", "tasks-knights-bg-20260927", "tasks-kodcode-20260927",
    "tasks-kodcode-20260927-bg", "tasks-synlogic-20260927", "tasks-reasoning-gym-20260927",
]
SPLIT_FILES = {"train": "episodes-train.jsonl", "validation": "episodes-validation.jsonl", "test": "episodes-test.jsonl"}
SOURCE_ROLES = {"passage": "passage", "schema": "schema", "tool": "tool_doc", "tool_doc": "tool_doc", "record": "record"}

_LICENCE_URLS = {
    "creativecommons.org/licenses/by/4.0": "CC-BY-4.0",
    "creativecommons.org/licenses/by-sa/4.0": "CC-BY-SA-4.0",
    "creativecommons.org/licenses/by-nc-sa/4.0": "CC-BY-NC-SA-4.0",
    "creativecommons.org/licenses/by-nc/4.0": "CC-BY-NC-4.0",
    "creativecommons.org/publicdomain/zero/1.0": "CC0-1.0",
    "arxiv.org/licenses/nonexclusive-distrib/1.0": "LicenseRef-arXiv-nonexclusive",
}


def corpus_short(corpus: str) -> str:
    name = re.sub(r"^tasks-", "", corpus)
    return re.sub(r"-?2026\d{4}", "", name)


def _source_licence(prov: dict) -> dict | None:
    raw = prov.get("license") or prov.get("licence")
    if not raw:
        return None
    raw = str(raw)
    for url, spdx in _LICENCE_URLS.items():
        if url in raw:
            return license_(spdx, "-nc" in spdx.lower())
    if raw.lower() in ("public domain", "pd"):
        return license_("LicenseRef-PublicDomain", False)
    return license_("LicenseRef-other", False, raw)


def _groups(domain: str, episode: dict, corpus: str) -> list[str]:
    prov = episode.get("provenance") or {}
    eid = episode.get("episode_id")
    if domain == "recall_text" and prov.get("document"):
        return [group_key("wiki-doc", prov["document"])]
    if domain == "parallel-recall" and prov.get("book"):
        return [group_key("bible-passage", f"{prov['book']}:{prov.get('chapter')}")]
    if domain == "citance_recall" and prov.get("cited"):
        return [group_key("openalex", prov["cited"].rsplit("/", 1)[-1])]
    if domain == "synth_people" and "person" in prov:
        return [group_key("synth-people", f"world{prov.get('world_seed', 0)}:person{prov['person']}")]
    if domain in ("spider", "bird", "spider_memory") and prov.get("db_id"):
        base = "bird" if domain == "bird" else "spider"
        return [group_key("sql-db", f"{base}:{prov['db_id']}")]
    if domain == "xlam":
        tools = sorted({s["text"].split("\n", 1)[0].removeprefix("Tool: ").strip()
                        for s in episode.get("supports", []) if s.get("text", "").startswith("Tool: ")})
        if tools:
            return [group_key("tool-schema", "+".join(tools))]
    if not eid:
        raise Reject("missing-group: no episode id")
    return [group_key(f"sdkb-{domain}", eid)]


def _target(episode: dict) -> tuple[dict, str, dict]:
    verify = episode.get("verify") or {}
    kind = verify.get("type")
    answer = strip_markup(episode.get("answer") or "").strip()
    details: dict = {}
    if kind == "sql":
        db = str(verify.get("db") or "").replace("/archive", ARCHIVE_ROOT, 1)
        details = {"db": db, "gold": verify.get("gold")}
        return {"kind": "sql", "value": answer or verify.get("gold"), "alternatives": []}, "sql-execution", details
    if kind == "calls":
        gold = verify.get("gold")
        if not gold:
            raise Reject("empty-target: calls")
        return {"kind": "calls", "value": gold, "alternatives": []}, "call-match", details
    if kind == "code":
        details = {"test": verify.get("test")}
        return {"kind": "text", "value": answer, "alternatives": []}, "unit-tests", details
    if kind == "knights":
        details = {"names": verify.get("names"), "solution": verify.get("solution")}
        return {"kind": "text", "value": answer, "alternatives": []}, "knights-solution", details
    if kind in ("exact", "reference"):
        return {"kind": "text", "value": answer, "alternatives": []}, f"{kind}-answer", details
    if kind in ("trajectory", "tau_bench") or episode.get("turns"):
        raise Reject(f"multi-turn-episode: {kind}")
    if not kind:
        return {"kind": "text", "value": answer, "alternatives": []}, "reference-answer", details
    details = {k: v for k, v in verify.items() if k != "type"}
    return {"kind": "text", "value": answer, "alternatives": []}, f"{kind}-check", details


def convert_episode(corpus: str, split: str, row_index: int, episode: dict, distractor_texts: dict) -> dict:
    prov = episode.get("provenance") or {}
    domain = prov.get("domain") or prov.get("dataset")
    if domain not in DOMAINS:
        raise Reject(f"unknown-domain: {domain}")
    family, upstream, (spdx, nc, lic_notes) = DOMAINS[domain]
    if corpus.endswith("-bg") or "-bg-" in corpus:
        family += "_bg"
    query = strip_markup(episode.get("query") or "")
    m = _STORED_RE.match(query)
    noun = m.group("noun").strip() if m else "records"
    request = query[m.end():].strip() if m else query.strip()
    if not request:
        raise Reject("empty-request")
    target, checked, details = _target(episode)
    if target["value"] in (None, "", []):
        raise Reject("empty-target")
    supports = episode.get("supports") or []
    if not supports:
        raise Reject("empty-source")
    required = set(episode.get("required_ids") or [])
    sources, required_idx = [], []
    for i, s in enumerate(supports):
        text = strip_markup(s.get("text") or "").strip()
        if not text:
            continue
        lic = _source_licence(s.get("provenance") or {})
        sources.append(source(SOURCE_ROLES.get(s.get("kind"), "record"), text, license=lic))
        if s.get("record_id") in required:
            required_idx.append(len(sources) - 1)
    if not sources:
        raise Reject("empty-source")
    distractors = [source("record", distractor_texts[n]) for n in (episode.get("neutral") or [])[:8] if distractor_texts.get(n)]
    record = {
        "version": VERSION,
        "id": f"sdkb:{corpus_short(corpus)}:" + re.sub(r"\s+", "_", str(episode.get("episode_id") or row_index)),
        "family": family.replace("-", "_"),
        "task": "consume",
        "sources": sources,
        "writer": {
            "instructions": f"Read the {noun} so that this request can be answered: {request}",
            "instructions_general": f"Read the {noun} so that later requests about them can be answered.",
            "result_type": "Neuralese<Records>",
            "context": [],
        },
        "consumer": {"context": [{"role": "user", "content": request}], "withheld": ["sources"]},
        "target": target,
        "outcome": {"label": "gold" if episode.get("support_annotation", "verified") == "verified" else "teacher",
                    "checked": checked, **({"details": details} if details else {})},
        "lineage": {"project": "schnitzeljagd", "store": corpus, "store_version": (re.search(r"2026\d{4}", corpus) or [None])[0],
                    "row": row_index, "upstream": upstream, "upstream_id": episode.get("episode_id"),
                    "upstream_revision": None, "teacher": None, "converter": CONVERTER, "sha256": "",
                    "notes": {"required_sources": required_idx, "query_time": episode.get("query_time")}},
        "license": license_(spdx, nc, lic_notes),
        "split": split,
        "split_groups": _groups(domain, episode, corpus),
    }
    if distractors:
        record["contrasts"] = {"purpose_pairs": [], "distractors": distractors}
    return seal(record)


def iter_corpus(corpus: str, limit_per_split: int | None, root: Path = CORPORA_DIR):
    """Yield (split, row_index, episode, distractor_texts) for a corpus, sampling the first rows of each split."""
    base = root / corpus
    sampled = []
    for split, filename in SPLIT_FILES.items():
        path = base / filename
        if not path.exists():
            continue
        lim = None if limit_per_split is None else (limit_per_split if split == "train" else max(1, limit_per_split // 5))
        for i, episode in jsonl_rows(path, lim):
            sampled.append((split, i, episode))
    wanted = {n for _, _, e in sampled for n in (e.get("neutral") or [])[:8]}
    texts: dict = {}
    if wanted and (base / "sources.jsonl").exists():
        with open(base / "sources.jsonl", encoding="utf-8") as stream:
            for line in stream:
                if not wanted:
                    break
                rec = json.loads(line)
                if rec.get("record_id") in wanted:
                    texts[rec["record_id"]] = strip_markup(rec.get("text") or "").strip()
                    wanted.discard(rec["record_id"])
    for split, i, episode in sampled:
        yield split, i, episode, texts
