/** Locally exported natlang checkpoints. The weights are generated by scripts/to_gguf.sh. */
export type BrowserModelManifest = { id: string; label: string; trainingRun: string;
  file: string; templateUrl: string; quant: string; bytes: number; sha256: string;
  contextTokens: number; url: string };

export const BROWSER_MODEL_CATALOG: readonly BrowserModelManifest[] = [{
  id: 'natlang-v8-failures-pilot-q4', label: 'natlang 350M v8 failures pilot Q4_K_M (smaller)',
  trainingRun: 'runs/lora-v8-failures-pilot',
  file: 'natlang-350M-v8-failures-pilot-Q4_K_M.gguf',
  templateUrl: '/models/templates/natlang-350M-v8-failures-pilot.jinja',
  quant: 'Q4_K_M', bytes: 229314496,
  sha256: 'a7fb96883bbe29a41c4f832b6d5c8fbfa6eebe0b2952814423cd9b1d14881cfd',
  contextTokens: 8192,
  url: '/models/natlang-350M-v8-failures-pilot-Q4_K_M.gguf',
}, {
  id: 'natlang-v8-failures-pilot', label: 'natlang 350M v8 failures pilot Q8_0',
  trainingRun: 'runs/lora-v8-failures-pilot',
  file: 'natlang-350M-v8-failures-pilot-Q8_0.gguf',
  templateUrl: '/models/templates/natlang-350M-v8-failures-pilot.jinja',
  quant: 'Q8_0', bytes: 379219904,
  sha256: '374f65708cadaf761667b661efb0eebcdd5caa4f522c95235065c00a465a74f8',
  contextTokens: 8192,
  url: '/models/natlang-350M-v8-failures-pilot-Q8_0.gguf',
}];

export type BrowserStorageStatus = { usage: number | null; quota: number | null;
  available: number | null; recommendedFree: number; enough: boolean | null; persisted: boolean | null };

type StorageProbe = { estimate(): Promise<{ usage?: number; quota?: number }>;
  persisted?(): Promise<boolean> };

/** Headroom covers the model file, cache metadata, and browser-specific temporary copies. */
export async function checkModelStorage(model: BrowserModelManifest,
  storage: StorageProbe | undefined = globalThis.navigator?.storage): Promise<BrowserStorageStatus> {
  const recommendedFree = Math.ceil(model.bytes * 1.5);
  if (!storage) return { usage: null, quota: null, available: null, recommendedFree,
    enough: null, persisted: null };
  const estimate = await storage.estimate();
  const usage = estimate.usage ?? null, quota = estimate.quota ?? null;
  const available = usage === null || quota === null ? null : Math.max(0, quota - usage);
  return { usage, quota, available, recommendedFree,
    enough: available === null ? null : available >= recommendedFree,
    persisted: storage.persisted ? await storage.persisted() : null };
}
