/** Locally exported natlang checkpoints. The weights are generated by scripts/to_gguf.sh. */
export type BrowserModelManifest = { id: string; label: string; trainingRun: string;
  file: string; templateUrl: string; quant: string; bytes: number; sha256: string;
  contextTokens: number; url: string };

export const BROWSER_MODEL_CATALOG: readonly BrowserModelManifest[] = [{
  id: 'natlang-v8-failures-pilot-q4', label: 'natlang 350M v8 failures pilot Q4_K_M (smaller)',
  trainingRun: 'runs/lora-v8-failures-pilot',
  file: 'natlang-350M-v8-failures-pilot-Q4_K_M.gguf',
  templateUrl: '/models/templates/natlang-350M-v8-failures-pilot.jinja',
  quant: 'Q4_K_M', bytes: 229314496,
  sha256: 'a7fb96883bbe29a41c4f832b6d5c8fbfa6eebe0b2952814423cd9b1d14881cfd',
  contextTokens: 8192,
  url: '/models/natlang-350M-v8-failures-pilot-Q4_K_M.gguf',
}, {
  id: 'natlang-v8-failures-pilot', label: 'natlang 350M v8 failures pilot Q8_0',
  trainingRun: 'runs/lora-v8-failures-pilot',
  file: 'natlang-350M-v8-failures-pilot-Q8_0.gguf',
  templateUrl: '/models/templates/natlang-350M-v8-failures-pilot.jinja',
  quant: 'Q8_0', bytes: 379219904,
  sha256: '374f65708cadaf761667b661efb0eebcdd5caa4f522c95235065c00a465a74f8',
  contextTokens: 8192,
  url: '/models/natlang-350M-v8-failures-pilot-Q8_0.gguf',
}];

export type BrowserModelCatalog = { schema: 'natlang.browser-model-catalog/1';
  defaultId: string; models: BrowserModelManifest[]; source: 'published' | 'builtin' };

/** One published pointer is shared by the playground, pilot, and application frontends. */
export async function loadBrowserModelCatalog(
  url = '/models/browser-catalog.json',
  fetcher: typeof fetch = globalThis.fetch,
): Promise<BrowserModelCatalog> {
  const response = await fetcher(url, { cache: 'no-store' });
  if (response.status === 404) return { schema: 'natlang.browser-model-catalog/1',
    defaultId: BROWSER_MODEL_CATALOG[0]!.id, models: [...BROWSER_MODEL_CATALOG], source: 'builtin' };
  if (!response.ok) throw new Error(`browser model catalog unavailable: HTTP ${response.status}`);
  const value = await response.json() as Partial<BrowserModelCatalog>;
  const models = value.models;
  if (value.schema !== 'natlang.browser-model-catalog/1' || !Array.isArray(models) || !models.length ||
      typeof value.defaultId !== 'string' ||
      models.some(model => !model || typeof model.id !== 'string' || !model.id ||
        typeof model.url !== 'string' || !model.url || typeof model.templateUrl !== 'string' ||
        !model.templateUrl || typeof model.label !== 'string' || !model.label ||
        typeof model.file !== 'string' || !model.file || !Number.isSafeInteger(model.bytes) ||
        model.bytes < 1 || !/^[a-f0-9]{64}$/.test(model.sha256) ||
        !Number.isSafeInteger(model.contextTokens) || model.contextTokens < 512) ||
      !models.some(model => model.id === value.defaultId) ||
      new Set(models.map(model => model.id)).size !== models.length)
    throw new Error('invalid published browser model catalog');
  return { schema: 'natlang.browser-model-catalog/1', defaultId: value.defaultId,
    models, source: 'published' };
}

export type BrowserStorageStatus = { usage: number | null; quota: number | null;
  available: number | null; recommendedFree: number; enough: boolean | null; persisted: boolean | null };

type StorageProbe = { estimate(): Promise<{ usage?: number; quota?: number }>;
  persisted?(): Promise<boolean> };

/** Headroom covers the model file, cache metadata, and browser-specific temporary copies. */
export async function checkModelStorage(model: BrowserModelManifest,
  storage: StorageProbe | undefined = globalThis.navigator?.storage): Promise<BrowserStorageStatus> {
  const recommendedFree = Math.ceil(model.bytes * 1.5);
  if (!storage) return { usage: null, quota: null, available: null, recommendedFree,
    enough: null, persisted: null };
  const estimate = await storage.estimate();
  const usage = estimate.usage ?? null, quota = estimate.quota ?? null;
  const available = usage === null || quota === null ? null : Math.max(0, quota - usage);
  return { usage, quota, available, recommendedFree,
    enough: available === null ? null : available >= recommendedFree,
    persisted: storage.persisted ? await storage.persisted() : null };
}
