/** Generated by scripts/update_llama_runtime.mjs; do not edit by hand. */
import type { LlamaRuntimeRelease } from './model/llama-runtime.js';

export const LLAMA_RUNTIME_RELEASE = Object.freeze({
  "version": "0.4.1",
  "build": 10964,
  "commit": "b29c606e2",
  "compatible": {
    "minimumVersion": "0.4.1",
    "maximumVersionExclusive": "0.5.0",
    "minimumBuild": 10964
  },
  "artifacts": [
    {
      "key": "linux-x64-cpu",
      "platform": "linux",
      "arch": "x64",
      "backend": "cpu",
      "archive": "tar.gz",
      "url": "https://github.com/ggml-org/llama.cpp/releases/download/b10964/llama-b10964-bin-ubuntu-x64.tar.gz",
      "bytes": 16825086,
      "sha256": "9abf88aea48a55d0f80edb1ee20220b186848cca0b4e919d71518cfd7ca67443"
    },
    {
      "key": "linux-arm64-cpu",
      "platform": "linux",
      "arch": "arm64",
      "backend": "cpu",
      "archive": "tar.gz",
      "url": "https://github.com/ggml-org/llama.cpp/releases/download/b10964/llama-b10964-bin-ubuntu-arm64.tar.gz",
      "bytes": 13451337,
      "sha256": "5f0e9c95d970892e43380f82ebcab960edfd20a1cd0f7abffa13b29fdb924949"
    },
    {
      "key": "darwin-arm64-metal",
      "platform": "darwin",
      "arch": "arm64",
      "backend": "metal",
      "archive": "tar.gz",
      "url": "https://github.com/ggml-org/llama.cpp/releases/download/b10964/llama-b10964-bin-macos-arm64.tar.gz",
      "bytes": 11149739,
      "sha256": "033c845c1df9bf945ff37bb193238b40910b2244be3e1e637b2ceb5878f1a6f5"
    },
    {
      "key": "darwin-x64-metal",
      "platform": "darwin",
      "arch": "x64",
      "backend": "metal",
      "archive": "tar.gz",
      "url": "https://github.com/ggml-org/llama.cpp/releases/download/b10964/llama-b10964-bin-macos-x64.tar.gz",
      "bytes": 11199948,
      "sha256": "03430a394d0a169a5e6d8f01c09f48cf58eb026af6fc95940a4a528e2e50cf38"
    },
    {
      "key": "win32-x64-cpu",
      "platform": "win32",
      "arch": "x64",
      "backend": "cpu",
      "archive": "zip",
      "url": "https://github.com/ggml-org/llama.cpp/releases/download/b10964/llama-b10964-bin-win-cpu-x64.zip",
      "bytes": 18427629,
      "sha256": "917f39c076402c421224824607397af20f53625a60defc20e8dd22446bf4c5d7"
    },
    {
      "key": "win32-arm64-cpu",
      "platform": "win32",
      "arch": "arm64",
      "backend": "cpu",
      "archive": "zip",
      "url": "https://github.com/ggml-org/llama.cpp/releases/download/b10964/llama-b10964-bin-win-cpu-arm64.zip",
      "bytes": 11996956,
      "sha256": "4b6a004b076eea47c318bea35cf1db2ff2bf037738b04645646ae8d7c3159478"
    }
  ]
} satisfies LlamaRuntimeRelease);
