/** Generated by scripts/publish_browser_model.mjs; do not edit by hand. */
export const DEFAULT_MODEL_RELEASE = Object.freeze({
  id: 'lfm2.5-350m-base-q8',
  label: 'LFM2.5-350M base · Q8_0',
  trainingRun: 'base model',
  file: 'LFM2.5-350M-Q8_0.gguf',
  quant: 'Q8_0',
  bytes: 379217632,
  sha256: 'be036a757295e550098b85e13f6af2735d0fa73b41e1156a40c7d8e8e32a5766',
  contextTokens: 8192,
  downloadUrl: 'https://huggingface.co/LiquidAI/LFM2.5-350M-GGUF/resolve/main/LFM2.5-350M-Q8_0.gguf',
  template: 'LFM2.5-350M.jinja',
});
